export const loginTypes = {
    LOGIN: 'LOGIN',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    LOGOUT: 'LOGOUT',
    TOGGLE_ERROR: 'TOGGLE_ERROR',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    LOGOUT: 'LOGOUT',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    RECENT_SEARCH: 'RECENT_SEARCH',
    UPDATE_ORDERS: 'UPDATE_ORDERS'
}

export const restaurantsTypes = {
    CREATE_RESTAURANT: 'CREATE_RESTAURANT',
    GET_RESTAURANT: 'GET_RESTAURANT',
    FILTER_TYPE: 'FILTER_TYPE',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    GET_MENU: 'GET_MENU'
}